#include "webctl.h"

/* Generated by WebControl/Tools/pack_web_assets.py. */
#include "webctl_assets.inc"

const WebCtlAsset *WebCtl_EmbeddedAssets(unsigned *asset_count)
{
    if (asset_count != 0) {
        *asset_count = webctl_asset_count;
    }
    return webctl_assets;
}
